version: '2'
services:
  mariadb-galera-server:
    image: mariadb:10.2
    network_mode: "container:galera"
    environment:
      TERM: "xterm"
      MYSQL_ROOT_PASSWORD: "${mysql_root_password}"
      MYSQL_DATABASE: "${mysql_database}"
      MYSQL_USER: "${mysql_user}"
      MYSQL_PASSWORD: "${mysql_password}"
    volumes_from:
      - 'mariadb-galera-data'
    labels:
      io.rancher.container.hostname_override: container_name
    entrypoint: bash -x /opt/rancher/start_galera
  mariadb-galera-data:
    image: mariadb:10.2
    network_mode: none
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - /var/lib/mysql
      - /etc/mysql/conf.d
      - /docker-entrypoint-initdb.d
      - /opt/rancher
    command: /bin/true
    labels:
      io.rancher.container.start_once: true
  galera-leader-forwarder:
    image: rancher/giddyup:v0.17.1
    network_mode: "container:galera"
    volumes_from:
     - 'mariadb-galera-data'
    command: "giddyup leader forward --src-port 3307 --dst-port 3306"
  galera:
    image: flaccid/galera-conf:v0.2.0
    labels:
      io.rancher.sidekicks: mariadb-galera-data,mariadb-galera-server,galera-leader-forwarder
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    volumes_from:
      - 'mariadb-galera-data'
    stdin_open: true
    tty: true
    command: /bin/bash
  galera-lb:
    ports:
    - 3306:3307/tcp
    tty: true
    image: rancher/lb-service-haproxy:v0.7.5
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
    links:
    - galera:galera
    stdin_open: true
