version: '2'
catalog:
  name: "Konga"
  version: "0.0.1"
  description: 'More than just another GUI to Kong Admin API.'
  questions:
    - variable: DB_ADAPTER
      label: 'Database Adapter'
      description: 'The database adapter for Konga.'
      type: enum
      options:
        - postgres
        - mysql
      required: true
      default: postgres
    - variable: DB_HOST
      label: 'Database Host'
      description: 'The database hostname or IP.'
      type: string
      required: true
      default: db-konga
    - variable: DB_PORT
      label: 'Database Port'
      description: 'The database port.'
      type: string
      required: true
      default: 5432
    - variable: DB_DATABASE
      label: 'Database Name'
      description: 'The database name or schema.'
      type: string
      required: true
      default: konga
    - variable: DB_USER
      label: 'Database User'
      description: 'The username for the Konga database.'
      type: string
      required: true
      default: konga
    - variable: DB_PASS
      label: 'Database Password'
      description: 'The password for the Konga database.'
      type: password
      required: true
      default: konga
    - variable: DB_SSL
      label: 'Use SSL'
      description: 'Use SSL for database connection.'
      type: enum
      options:
        - true
        - false
      required: true
    - variable: NODE_ENV
      label: 'Node Environment'
      description: 'The environment level to use.'
      type: enum
      options:
        - production
        - development
      default: production
      required: true
    - variable: DOCKER_ENTRYPOINT
      label: 'Docker Entrypoint'
      description: 'Optional, override of the docker entrypoint.'
      type: string
services:
  konga:
    scale: 1
    start_on_create: true
  lb:
   start_on_create: true
   lb_config:
     certs: []
     port_rules:
     - priority: 1
       protocol: http
       service: konga
       source_port: 8004
       target_port: 1337
   health_check:
     response_timeout: 2000
     healthy_threshold: 2
     port: 42
     unhealthy_threshold: 3
     initializing_timeout: 60000
     interval: 2000
     reinitializing_timeout: 60000
