version: '2'
catalog:
  name: "Konga"
  version: "0.0.1"
  description: 'More than just another GUI to Kong Admin API.'
services:
  konga:
    scale: 1
    start_on_create: true
  lb-konga:
   start_on_create: true
   lb_config:
     certs: []
     port_rules:
     - priority: 1
       protocol: http
       service: konga
       source_port: 8004
       target_port: 1337
   health_check:
     response_timeout: 2000
     healthy_threshold: 2
     port: 42
     unhealthy_threshold: 3
     initializing_timeout: 60000
     interval: 2000
     reinitializing_timeout: 60000
