version: '2'
services:
  ranch53:
    scale: 1
    start_on_create: true
catalog:
  name: "ranch53"
  version: "0.0.1"
  description: "Simple service that updates Route 53 based on labels on Rancher services."
  questions:
  - variable: "AWS_ACCESS_KEY_ID"
    label: "AWS Access Key ID"
    description: "AWS Access Key ID to update Route 53."
    type "string"
    required: true
  - variable: "AWS_SECRET_ACCESS_KEY"
    label: "AWS Secret Access Key"
    description: "AWS Secret Access Key to update Route 53."
    type "string"
    required: true
  - variable: "FORWARD_PROXY"
    label: "Forward Proxy"
    description: "Optional, a forward proxy to use (in format, user:password@hostname:port)."
    type: "string"
    required: false
