version: '2'
catalog:
  name: Prometheus
  version: 2.1.0-1
  description: "The Prometheus monitoring system and time series database."
  maintainer: "Chris Fordham <chris@fordham-nagy.id.au>"
  questions:
    - variable: PROMETHEUS_DOCKER_IMAGE
      label: "Prometheus Docker Image"
      description: "Docker image to use for Prometheus."
      default: 'flaccid/prometheus:latest'
      required: true
      type: string
    - variable: PROMETHEUS_DATA_RANCHER_NFS_ENABLED
      label: Enable Rancher NFS
      description: Whether to use the Rancher NFS driver for Prometheus data (Rancher NFS must be previously deployed from the catalog).
      required: false
      default: false
      type: boolean

    - variable: PROMETHEUS_PUBLIC_LB
      label: Enable Public LB
      description: Whether to expose the load balancer public or keep internal.
      required: true
      default: true
      type: boolean
    - variable: PROMETHEUS_GLOBAL_LB
      label: Enable Global LB
      description: Whether to make the load balancer a global service.
      required: true
      default: false
      type: boolean

    - variable: PROMETHEUS_LB_PORT
      description: "Port for access to Prometheus through the load balancer."
      label: "Load Balancer Port"
      required: true
      default: 9090
      type: "int"
    - variable: SOFT_AFFINITY_SCHEDULING
      label: Soft Affinity Scheduling
      description: Whether to use soft host affinity scheduling with Rancher.
      required: false
      default: true
      type: boolean

    - variable: PROMETHEUS_LB_HOST_LABEL
      label: Load Balancer Host Label
      description: Host label (soft affinity is default) for scheduling of the load balancer service.
      required: true
      default: "tier=public"
      type: string
    - variable: PROMETHEUS_SERVER_HOST_LABEL
      label: Grafana Host Label
      description: Host label (soft affinity is default) for scheduling of the Prometheus service.
      required: true
      default: "tier=private"
      type: string

    - variable: "SETUP_GRAFANA"
      description: "Grafana, the open platform for analytics and monitoring."
      label: "Setup Grafana"
      required: false
      type: boolean
      default: true
    - variable: "SETUP_CADVISOR"
      description: "Analyzes resource usage and performance characteristics of running containers."
      label: "Setup cAdvisor"
      required: false
      type: boolean
      default: true

    - variable: "SETUP_NODE_EXPORTER"
      description: "Prometheus exporter for machine metrics, written in Go with pluggable metric collectors."
      label: "Setup Node Exporter"
      required: false
      type: boolean
      default: true
    - variable: "SETUP_RANCHER_EXPORTER"
      description: "Exposes Service/Stack/Host status from the Rancher API, to a Prometheus compatible interface."
      label: "Setup Rancher Exporter"
      required: false
      type: boolean
      default: true

    - variable: "SETUP_BLACKBOX_EXPORTER"
      description: "The blackbox exporter allows blackbox probing of endpoints over HTTP, HTTPS, DNS, TCP and ICMP."
      label: "Setup Blackbox Exporter"
      required: false
      type: boolean
      default: true
    - variable: "SETUP_RANCHER_CRONTAB_EXPORTER"
      description: "Scrapes the rancher-crontab infrastructure service exporter (you must have this installed already from the catalog)."
      label: "Scrape Rancher Crontab Exporter"
      required: false
      type: boolean
      default: false
services:
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        path: ''
        priority: 1
        protocol: http
        service: prometheus
        source_port: ${PROMETHEUS_LB_PORT}
        target_port: 9090
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  prometheus:
    scale: 1
    start_on_create: true
  prometheus-conf:
    scale: 1
    start_on_create: true
