version: '2'
catalog:
  name: Prometheus
  version: 2.1.0-1
  description: "The Prometheus monitoring system and time series database."
  maintainer: "Chris Fordham <chris@fordham-nagy.id.au>"
  questions:
    - variable: "SETUP_GRAFANA"
      description: "Grafana, the open platform for analytics and monitoring."
      label: "Setup Grafana"
      required: false
      type: boolean
      default: true
services:
  prometheus:
    scale: 1
    start_on_create: true
