version: '2'
catalog:
  name: Prometheus
  version: 2.1.0-1
  description: "The Prometheus monitoring system and time series database."
services:
  prometheus:
    scale: 1
    start_on_create: true
  grafana:
    scale: 1
    start_on_create: true
