version: '2'
catalog:
  name: Prometheus
  version: 2.1.0-1
  description: "The Prometheus monitoring system and time series database."
  maintainer: "Chris Fordham <chris@fordham-nagy.id.au>"
  questions:
    - variable: "SETUP_GRAFANA"
      description: "Grafana, the open platform for analytics and monitoring."
      label: "Setup Grafana"
      required: false
      type: boolean
      default: true
    - variable: "SETUP_NODE_EXPORTER"
      description: "Prometheus exporter for machine metrics, written in Go with pluggable metric collectors."
      label: "Setup Node Exporter"
      required: false
      type: boolean
      default: true
    - variable: "SETUP_RANCHER_EXPORTER"
      description: "Exposes Service/Stack/Host status from the Rancher API, to a Prometheus compatible interface."
      label: "Setup Rancher Exporter"
      required: false
      type: boolean
      default: true
    - variable: "SETUP_RANCHER_CRONTAB_EXPORTER"
      description: "Scrapes the rancher-crontab infrastructure service exporter (you must have this installed already from the catalog)."
      label: "Scrape Rancher Crontab Exporter"
      required: false
      type: boolean
      default: false
    - variable: "SETUP_CADVISOR"
      description: "Analyzes resource usage and performance characteristics of running containers."
      label: "Setup cAdvisor"
      required: false
      type: boolean
      default: true
services:
  prometheus:
    scale: 1
    start_on_create: true
