version: '2'
catalog:
  name: "Kong Enterprise Edition"
  version: "0.11.0.3"
  description: 'The World’s Most Popular Open Source Microservice API Gateway.'
  questions:
    - variable: LICENSE_DATA
      label: 'License Data'
      description: 'The license data provided by Mashape (JSON format).'
      type: string
      required: true
    - variable: LB_ACCESS
      label: 'Load Balancer Access'
      description: 'Expose the load balancer publicly or keep internal (use your own reversy proxy or edit after).'
      type: enum
      options:
        - Internal
        - Public
      required: true
      default: Internal
services:
  migrations:
    scale: 1
    start_on_create: true
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: kong-ee
        source_port: 8000
        target_port: 8000
      - priority: 2
        protocol: tcp
        service: kong-ee
        source_port: 8001
        target_port: 8001
      - priority: 3
        protocol: tcp
        service: kong-ee
        source_port: 8002
        target_port: 8002
      - priority: 4
        protocol: tcp
        service: kong-ee
        source_port: 8443
        target_port: 8443
      - priority: 5
        protocol: tcp
        service: kong-ee
        source_port: 8444
        target_port: 8444
      - priority: 6
        protocol: tcp
        service: kong-ee
        source_port: 8445
        target_port: 8445
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  db:
    scale: 1
    start_on_create: true
  kong-ee:
    scale: 1
    start_on_create: true
