version: '2'
services:
  migrations:
    scale: 1
    start_on_create: true
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: kong
        source_port: 8000
        target_port: 8000
      - priority: 2
        protocol: tcp
        service: kong
        source_port: 8443
        target_port: 8443
      - priority: 3
        protocol: tcp
        service: kong
        source_port: 8001
        target_port: 8001
      - priority: 4
        protocol: tcp
        service: kong
        source_port: 8002
        target_port: 8002
      - priority: 5
        protocol: tcp
        service: kong
        source_port: 8444
        target_port: 8444
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  db:
    scale: 1
    start_on_create: true
  kong:
    scale: 1
    start_on_create: true
