.catalog:
  name: "Graylog"
  version: "v2.3.0-1"
  description: "Open source log management that actually works."
  questions:
    - variable: graylog_lb_port
      description: "Public port for access to Graylog through the load balancer"
      label: "Graylog Public LB Port"
      required: true
      default: 9000
      type: "int"
    - variable: graylog_password
      description: "Password in sha2"
      label: "SHA2 Password"
      type: password
      required: true
    - variable: graylog_secret
      description: "Password secret"
      label: "Password secret"
      type: password
      required: true
    - variable: graylog_fqdn
      description: "FQDN of Graylog"
      label: "FQDN"
      type: "string"
      default: "localhost"
      required: true
