.catalog:
  name: "Graylog"
  version: "v2.3.0-1"
  description: "Open source log management that actually works."
  questions:
    - variable: graylog_lb_port
      description: "Public port for access to Graylog through the load balancer"
      label: "Graylog Public LB Port"
      required: true
      default: 9000
      type: "int"
    - variable: graylog_password
      description: "Password in SHA2 (default hash is of 'admin')."
      label: "SHA2 Password"
      type: password
      required: true
      default: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
    - variable: graylog_secret
      description: "Password secret"
      label: "Password secret"
      type: password
      default: "replacethiswithyourownsecret!"
      required: true
    - variable: graylog_fqdn
      description: "FQDN of Graylog"
      label: "FQDN"
      type: "string"
      default: "localhost"
      required: true
    - variable: graylog_lb_host_label
      label: Graylog LB Host Label
      description: Host label (soft affinity) for scheduling of the load balancer service.
      required: true
      default: "graylog_lb=true"
      type: string
    - variable: graylog_server_host_label
      label: Graylog Server Host Label
      description: Host label (soft affinity) for scheduling of the Graylog service.
      required: true
      default: "graylog_server=true"
      type: string
    - variable: enable_logspout
      label: Logspout Setup
      description: Run a service for logspout to send container logs.
      default: true
      required: false
      type: boolean
version: '2'
services:
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        path: ''
        priority: 1
        protocol: http
        service: graylog
        source_port: 9000
        target_port: 9000
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  elasticsearch:
    scale: 1
    start_on_create: true
  kopf:
    scale: 1
    start_on_create: true
  graylog:
    scale: 1
    start_on_create: true
  graylog-data:
    scale: 1
    start_on_create: true
  mongo-data:
    scale: 1
    start_on_create: true
  mongo:
    scale: 1
    start_on_create: true
