version: '2'
catalog:
  name: Grafana
  version: v5-alpha
  description: |
    Data visualization & Monitoring with support for Graphite, InfluxDB, Prometheus, Elasticsearch and many more databases.
  maintainer: "Chris Fordham <chris@fordham-nagy.id.au>"
