version: '2'
catalog:
  name: Grafana
  version: v5-alpha
  description: |
    Data visualization & Monitoring with support for Graphite, InfluxDB, Prometheus, Elasticsearch and many more databases.
  maintainer: "Chris Fordham <chris@fordham-nagy.id.au>"
  questions:
    - variable: GRAFANA_PUBLIC_LB_PORT
      description: "Public port for access to Grafana through the load balancer."
      label: "Load Balancer Public Port"
      required: true
      default: 3000
      type: "int"
    - variable: GRAFANA_DOCKER_IMAGE
      label: "Grafana Docker Image"
      description: "Docker image to use for Grafana."
      default: 'flaccid/grafana:latest'
      required: true
      type: string

    - variable: GRAFANA_ADMIN_USER
      label: Admin Username
      description: Grafin administration user name.
      default: admin
      type: string
    - variable: GRAFANA_ADMIN_PASSWORD
      label: Admin Password
      description: "Grafana administration password (default: admin)."
      default: admin
      type: password

    - variable: GRAFANA_DATA_RANCHER_NFS_ENABLED
      label: Enable Rancher NFS
      description: Whether to use the Rancher NFS driver for Grafana data (Rancher NFS must be previously deployed from the catalog).
      required: false
      default: false
      type: boolean
    - variable: GRAFANA_PLUGINS_INSTALL
      description: "Grafana plugins to install (comma-separated plugin-ids)."
      label: "Install Plugins"
      required: false
      default: "grafana-clock-panel"
      type: "string"

    - variable: GRAFANA_LB_HOST_LABEL
      label: Load Balancer Host Label
      description: Host label (soft by default) for scheduling of the load balancer service.
      required: true
      default: "tier=public"
      type: string
    - variable: GRAFANA_SERVER_HOST_LABEL
      label: Grafana Host Label
      description: Host label (soft by default) for scheduling of the Grafana service.
      required: true
      default: "tier=private"
      type: string

    - variable: SOFT_AFFINITY_SCHEDULING
      label: Soft Affinity Scheduling
      description: Whether to use soft host affinity scheduling with Rancher.
      required: false
      default: true
      type: boolean
    - variable: GRAFANA_SECURITY_SECRET_KEY
      label: Grafana Signing Security Key
      description: A security key for signing.
      type: password
      required: true

    - variable: PROMETHEUS_DATASOURCE_ENABLED
      label: Enable Prometheus Datasource
      description: Enables and sets up the Prometheus data source.
      required: false
      default: false
      type: boolean
    - variable: PROMETHEUS_ACCESS_MODE
      label: Prometheus Access Mode
      description: Access Prometheus direct or via proxy.
      required: false
      default: proxy
      type: string

    - variable: PROMETHEUS_URL
      label: Prometheus URL
      description: The URL to connect to Prometheus with.
      required: false
      default: http://prometheus.prometheus.rancher.internal:9090/
      type: string
services:
  grafana:
    scale: 1
    start_on_create: true
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        priority: 1
        protocol: http
        service: grafana
        source_port: ${GRAFANA_PUBLIC_LB_PORT}
        target_port: 3000
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
