version: '2'
catalog:
  name: Grafana
  version: v5-alpha
  description: |
    Data visualization & Monitoring with support for Graphite, InfluxDB, Prometheus, Elasticsearch and many more databases.
  maintainer: "Chris Fordham <chris@fordham-nagy.id.au>"
  questions:
    - variable: GRAFANA_PUBLIC_LB_PORT
      description: "Public port for access to Grafana through the load balancer."
      label: "Load Balancer Public Port"
      required: true
      default: 9000
      type: "int"
    - variable: GRAFANA_LB_HOST_LABEL
      label: Load Balancer Host Label
      description: Host label (soft affinity) for scheduling of the load balancer service.
      required: true
      default: "public=true"
      type: string
    - variable: GRAFANA_SERVER_HOST_LABEL
      label: Grafana Host Label
      description: Host label (soft affinity) for scheduling of the Grafana service.
      required: true
      default: "private=true"
      type: string
services:
  grafana:
    scale: 1
    start_on_create: true
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        priority: 1
        protocol: http
        service: grafana
        source_port: ${GRAFANA_PUBLIC_LB_PORT}
        target_port: 3000
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
