.catalog:
  name: OpenVPN Azure AD
  version: 0.1.0
  description: |
    OpenVPN for Rancher with Azure AD authentication
  maintainer: "Chris Fordham <chris@fordham-nagy.id.au>"
  questions:
    - variable: "CLIENT_ID"
      description: "Azure AD application Client ID."
      label: "Client ID"
      required: true
      type: "string"
    - variable: "TENANT_ID"
      description: "Azure AD application Tenant ID."
      label: "Tenant ID"
      required: true
      type: "string"
    - variable: "Privileged"
      description: "Run as a privileged container service."
      label: "Privileged"
      required: true
      type: boolean
      default: true
version: '2'
services:
  openvpn-server:
    scale: 1
    start_on_create: true
