.catalog:
  name: OpenVPN Azure AD
  version: 0.1.0
  description: |
    OpenVPN for Rancher with Azure AD authentication
  minimum_rancher_version: v0.56.0
  maintainer: "Chris Fordham <chris@fordham-nagy.id.au>"
  questions:
    - variable: "CLIENT_ID"
      description: "Azure AD application Client ID"
      label: "Client ID"
      required: true
      type: "string"
    - variable: "TENANT_ID"
      description: "Azure AD application Tenant ID"
      label: "Tenant ID"
      required: true
      type: "string"
